version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: replicated-search-prometheus
    volumes:
      - ./prometheus.yml.template:/etc/prometheus/prometheus.yml.template
    ports:
      - "${PROMETHEUS_PORT}:9090"
    env_file:
      - ../.env

  grafana:
    image: grafana/grafana:latest
    container_name: replicated-search-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
    env_file:
      - ../.env
