apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicated-search-indexing-system
spec:
  replicas: ${ENGINE_REPLICAS}
  selector:
    matchLabels:
      app: replicated-search-indexing-system
  template:
    metadata:
      labels:
        app: replicated-search-indexing-system
    spec:
      containers:
        - name: replicated-search-indexing-system
          image: "${ENGINE_IMAGE}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: ${HTTP_PORT}
            - name: grpc
              containerPort: ${GRPC_PORT}
            - name: mgmt
              containerPort: ${MANAGEMENT_PORT}
          envFrom:
            - configMapRef:
                name: engine-config
            - secretRef:
                name: engine-secret
          volumeMounts:
            - name: engine-index
              mountPath: /data/index
      volumes:
        - name: engine-index
          emptyDir: {}
