apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: replicated-search-indexing-system-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ${ENGINE_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: replicated-search-indexing-system-svc
                port:
                  number: ${HTTP_PORT}
