apiVersion: v1
kind: Service
metadata:
  name: replicated-search-indexing-system-svc
spec:
  selector:
    app: replicated-search-indexing-system
  ports:
    - name: http
      port: ${HTTP_PORT}
      targetPort: http
    - name: grpc
      port: ${GRPC_PORT}
      targetPort: grpc
    - name: management
      port: ${MANAGEMENT_PORT}
      targetPort: mgmt
  type: ClusterIP
